apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  labels:
    type: myapp
spec:
  containers:
    - image: nginx
      name: inginx-container
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata: 
  name: mypod1
  labels:
    type: myapp
spec:
  containers:
    - image: nginx
      name: inginx-container
      ports:
        - containerPort: 80
