apiVersion: v1
kind: Pod
metadata:
  name: argocd-pod2
  namespace: default
  labels:
    type: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: argocd-pod3
  namespace: default
  labels:
    type: myapp
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
